
package com.phcarvalho.model.communication.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IQueueHandler", targetNamespace = "http://webservice.communication.model.phcarvalho.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IQueueHandler {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://webservice.communication.model.phcarvalho.com/", className = "com.phcarvalho.model.communication.webservice.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://webservice.communication.model.phcarvalho.com/", className = "com.phcarvalho.model.communication.webservice.CreateResponse")
    @Action(input = "http://webservice.communication.model.phcarvalho.com/IQueueHandler/createRequest", output = "http://webservice.communication.model.phcarvalho.com/IQueueHandler/createResponse")
    public void create(
            @WebParam(name = "arg0", targetNamespace = "")
                    User arg0);

}
